title: MiloSpot Pages
description: I do tech stuff
baseurl: ""
url: "milospot.github.io"
repository: milospot/milospot.github.io

theme: just-the-docs

color_scheme: dark

# # Aux links for the upper right navigation
aux_links:
  "Just the Docs on GitHub":
    - "//github.com/just-the-docs/just-the-docs"


# logo: "/assets/images/just-the-docs.png"
# favicon_ico: "/assets/images/favicon.ico"

version: 0.0.1

mermaid:
  # Version of mermaid library
  # Pick an available version from https://cdn.jsdelivr.net/npm/mermaid/
  version: "9.1.3"


# # Makes Aux links open in a new tab. Default is false
# aux_links_new_tab: false


# # Heading anchor links appear on hover over h1-h6 tags in page content
# # allowing users to deep link to a particular heading on a page.
# #
# # Supports true (default) or false
# heading_anchors: true

collections_dir: collections

collections:
  tests:
    # permalink: "/:collection/:path/"
    output: true

just_the_docs:
  collections:
    tests:
      name: Tests


